# Generated by Django 5.2.17 on 2026-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("registrations", "Registration Report"),
                            ("appointments", "Appointment Report"),
                            ("orders", "Order Report"),
                            ("lab_tests", "Lab Test Report"),
                            ("payments", "Payment Report"),
                            ("subscriptions", "Subscription Report"),
                            ("applications", "Application Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
