# Generated by Django 5.2.17 on 2026-10-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantsettings",
            name="assistant_type",
            field=models.CharField(
                choices=[("tatito_ai", "Tatito AI"), ("aria", "Aria")],
                default="tatito_ai",
                max_length=30,
                unique=True,
            ),
        ),
    ]
