// Comprehensive dataset of world country phone codes and national mobile digit lengths
export const countryPhoneCodes = [
  { name: 'India', code: '+91', iso: 'IN', digits: 10, flag: '🇮🇳' },
  { name: 'United States', code: '+1', iso: 'US', digits: 10, flag: '🇺🇸' },
  { name: 'United Kingdom', code: '+44', iso: 'GB', digits: 10, flag: '🇬🇧' },
  { name: 'Canada', code: '+1', iso: 'CA', digits: 10, flag: '🇨🇦' },
  { name: 'Australia', code: '+61', iso: 'AU', digits: 9, flag: '🇦🇺' },
  { name: 'United Arab Emirates', code: '+971', iso: 'AE', digits: 9, flag: '🇦🇪' },
  { name: 'Saudi Arabia', code: '+966', iso: 'SA', digits: 9, flag: '🇸🇦' },
  { name: 'Singapore', code: '+65', iso: 'SG', digits: 8, flag: '🇸🇬' },
  { name: 'Germany', code: '+49', iso: 'DE', digits: 10, flag: '🇩🇪' },
  { name: 'France', code: '+33', iso: 'FR', digits: 9, flag: '🇫🇷' },
  { name: 'Afghanistan', code: '+93', iso: 'AF', digits: 9, flag: '🇦🇫' },
  { name: 'Albania', code: '+355', iso: 'AL', digits: 9, flag: '🇦🇱' },
  { name: 'Algeria', code: '+213', iso: 'DZ', digits: 9, flag: '🇩🇿' },
  { name: 'Andorra', code: '+376', iso: 'AD', digits: 6, flag: '🇦🇩' },
  { name: 'Angola', code: '+244', iso: 'AO', digits: 9, flag: '🇦🇴' },
  { name: 'Argentina', code: '+54', iso: 'AR', digits: 10, flag: '🇦🇷' },
  { name: 'Armenia', code: '+374', iso: 'AM', digits: 8, flag: '🇦🇲' },
  { name: 'Austria', code: '+43', iso: 'AT', digits: 10, flag: '🇦🇹' },
  { name: 'Azerbaijan', code: '+994', iso: 'AZ', digits: 9, flag: '🇦🇿' },
  { name: 'Bahamas', code: '+1-242', iso: 'BS', digits: 10, flag: '🇧🇸' },
  { name: 'Bahrain', code: '+973', iso: 'BH', digits: 8, flag: '🇧🇭' },
  { name: 'Bangladesh', code: '+880', iso: 'BD', digits: 10, flag: '🇧🇩' },
  { name: 'Barbados', code: '+1-246', iso: 'BB', digits: 10, flag: '🇧🇧' },
  { name: 'Belarus', code: '+375', iso: 'BY', digits: 9, flag: '🇧🇾' },
  { name: 'Belgium', code: '+32', iso: 'BE', digits: 9, flag: '🇧🇪' },
  { name: 'Belize', code: '+501', iso: 'BZ', digits: 7, flag: '🇧🇿' },
  { name: 'Benin', code: '+229', iso: 'BJ', digits: 8, flag: '🇧🇯' },
  { name: 'Bhutan', code: '+975', iso: 'BT', digits: 8, flag: '🇧🇹' },
  { name: 'Bolivia', code: '+591', iso: 'BO', digits: 8, flag: '🇧🇴' },
  { name: 'Bosnia & Herzegovina', code: '+387', iso: 'BA', digits: 8, flag: '🇧🇦' },
  { name: 'Botswana', code: '+267', iso: 'BW', digits: 8, flag: '🇧🇼' },
  { name: 'Brazil', code: '+55', iso: 'BR', digits: 11, flag: '🇧🇷' },
  { name: 'Brunei', code: '+673', iso: 'BN', digits: 7, flag: '🇧🇳' },
  { name: 'Bulgaria', code: '+359', iso: 'BG', digits: 9, flag: '🇧🇬' },
  { name: 'Burkina Faso', code: '+226', iso: 'BF', digits: 8, flag: '🇧🇫' },
  { name: 'Burundi', code: '+257', iso: 'BI', digits: 8, flag: '🇧🇮' },
  { name: 'Cambodia', code: '+855', iso: 'KH', digits: 9, flag: '🇰🇭' },
  { name: 'Cameroon', code: '+237', iso: 'CM', digits: 9, flag: '🇨🇲' },
  { name: 'Chile', code: '+56', iso: 'CL', digits: 9, flag: '🇨🇱' },
  { name: 'China', code: '+86', iso: 'CN', digits: 11, flag: '🇨🇳' },
  { name: 'Colombia', code: '+57', iso: 'CO', digits: 10, flag: '🇨🇴' },
  { name: 'Costa Rica', code: '+506', iso: 'CR', digits: 8, flag: '🇨🇷' },
  { name: 'Croatia', code: '+385', iso: 'HR', digits: 9, flag: '🇭🇷' },
  { name: 'Cuba', code: '+53', iso: 'CU', digits: 8, flag: '🇨🇺' },
  { name: 'Cyprus', code: '+357', iso: 'CY', digits: 8, flag: '🇨🇾' },
  { name: 'Czech Republic', code: '+420', iso: 'CZ', digits: 9, flag: '🇨🇿' },
  { name: 'Denmark', code: '+45', iso: 'DK', digits: 8, flag: '🇩🇰' },
  { name: 'Djibouti', code: '+253', iso: 'DJ', digits: 8, flag: '🇩🇯' },
  { name: 'Dominican Republic', code: '+1-809', iso: 'DO', digits: 10, flag: '🇩🇴' },
  { name: 'Ecuador', code: '+593', iso: 'EC', digits: 9, flag: '🇪🇨' },
  { name: 'Egypt', code: '+20', iso: 'EG', digits: 10, flag: '🇪🇬' },
  { name: 'El Salvador', code: '+503', iso: 'SV', digits: 8, flag: '🇸🇻' },
  { name: 'Estonia', code: '+372', iso: 'EE', digits: 8, flag: '🇪🇪' },
  { name: 'Ethiopia', code: '+251', iso: 'ET', digits: 9, flag: '🇪🇹' },
  { name: 'Fiji', code: '+679', iso: 'FJ', digits: 7, flag: '🇫🇯' },
  { name: 'Finland', code: '+358', iso: 'FI', digits: 9, flag: '🇫🇮' },
  { name: 'Georgia', code: '+995', iso: 'GE', digits: 9, flag: '🇬🇪' },
  { name: 'Ghana', code: '+233', iso: 'GH', digits: 9, flag: '🇬🇭' },
  { name: 'Greece', code: '+30', iso: 'GR', digits: 10, flag: '🇬🇷' },
  { name: 'Guatemala', code: '+502', iso: 'GT', digits: 8, flag: '🇬🇹' },
  { name: 'Honduras', code: '+504', iso: 'HN', digits: 8, flag: '🇭🇳' },
  { name: 'Hong Kong', code: '+852', iso: 'HK', digits: 8, flag: '🇭🇰' },
  { name: 'Hungary', code: '+36', iso: 'HU', digits: 9, flag: '🇭🇺' },
  { name: 'Iceland', code: '+354', iso: 'IS', digits: 7, flag: '🇮🇸' },
  { name: 'Indonesia', code: '+62', iso: 'ID', digits: 10, flag: '🇮🇩' },
  { name: 'Iran', code: '+98', iso: 'IR', digits: 10, flag: '🇮🇷' },
  { name: 'Iraq', code: '+964', iso: 'IQ', digits: 10, flag: '🇮🇶' },
  { name: 'Ireland', code: '+353', iso: 'IE', digits: 9, flag: '🇮🇪' },
  { name: 'Israel', code: '+972', iso: 'IL', digits: 9, flag: '🇮🇱' },
  { name: 'Italy', code: '+39', iso: 'IT', digits: 10, flag: '🇮🇹' },
  { name: 'Jamaica', code: '+1-876', iso: 'JM', digits: 10, flag: '🇯🇲' },
  { name: 'Japan', code: '+81', iso: 'JP', digits: 10, flag: '🇯🇵' },
  { name: 'Jordan', code: '+962', iso: 'JO', digits: 9, flag: '🇯🇴' },
  { name: 'Kazakhstan', code: '+7', iso: 'KZ', digits: 10, flag: '🇰🇿' },
  { name: 'Kenya', code: '+254', iso: 'KE', digits: 9, flag: '🇰🇪' },
  { name: 'Kuwait', code: '+965', iso: 'KW', digits: 8, flag: '🇰🇼' },
  { name: 'Laos', code: '+856', iso: 'LA', digits: 9, flag: '🇱🇦' },
  { name: 'Latvia', code: '+371', iso: 'LV', digits: 8, flag: '🇱🇻' },
  { name: 'Lebanon', code: '+961', iso: 'LB', digits: 8, flag: '🇱🇧' },
  { name: 'Libya', code: '+218', iso: 'LY', digits: 9, flag: '🇱🇾' },
  { name: 'Lithuania', code: '+370', iso: 'LT', digits: 8, flag: '🇱🇹' },
  { name: 'Luxembourg', code: '+352', iso: 'LU', digits: 9, flag: '🇱🇺' },
  { name: 'Malaysia', code: '+60', iso: 'MY', digits: 10, flag: '🇲🇾' },
  { name: 'Maldives', code: '+960', iso: 'MV', digits: 7, flag: '🇲🇻' },
  { name: 'Malta', code: '+356', iso: 'MT', digits: 8, flag: '🇲🇹' },
  { name: 'Mauritius', code: '+230', iso: 'MU', digits: 8, flag: '🇲🇺' },
  { name: 'Mexico', code: '+52', iso: 'MX', digits: 10, flag: '🇲🇽' },
  { name: 'Monaco', code: '+377', iso: 'MC', digits: 8, flag: '🇲🇨' },
  { name: 'Mongolia', code: '+976', iso: 'MN', digits: 8, flag: '🇲🇳' },
  { name: 'Montenegro', code: '+382', iso: 'ME', digits: 8, flag: '🇲🇪' },
  { name: 'Morocco', code: '+212', iso: 'MA', digits: 9, flag: '🇲🇦' },
  { name: 'Myanmar', code: '+95', iso: 'MM', digits: 9, flag: '🇲🇲' },
  { name: 'Nepal', code: '+977', iso: 'NP', digits: 10, flag: '🇳🇵' },
  { name: 'Netherlands', code: '+31', iso: 'NL', digits: 9, flag: '🇳🇱' },
  { name: 'New Zealand', code: '+64', iso: 'NZ', digits: 9, flag: '🇳🇿' },
  { name: 'Nigeria', code: '+234', iso: 'NG', digits: 10, flag: '🇳🇬' },
  { name: 'North Macedonia', code: '+389', iso: 'MK', digits: 8, flag: '🇲🇰' },
  { name: 'Norway', code: '+47', iso: 'NO', digits: 8, flag: '🇳🇴' },
  { name: 'Oman', code: '+968', iso: 'OM', digits: 8, flag: '🇴🇲' },
  { name: 'Pakistan', code: '+92', iso: 'PK', digits: 10, flag: '🇵🇰' },
  { name: 'Panama', code: '+507', iso: 'PA', digits: 8, flag: '🇵🇦' },
  { name: 'Paraguay', code: '+595', iso: 'PY', digits: 9, flag: '🇵🇾' },
  { name: 'Peru', code: '+51', iso: 'PE', digits: 9, flag: '🇵🇪' },
  { name: 'Philippines', code: '+63', iso: 'PH', digits: 10, flag: '🇵🇭' },
  { name: 'Poland', code: '+48', iso: 'PL', digits: 9, flag: '🇵🇱' },
  { name: 'Portugal', code: '+351', iso: 'PT', digits: 9, flag: '🇵🇹' },
  { name: 'Qatar', code: '+974', iso: 'QA', digits: 8, flag: '🇶🇦' },
  { name: 'Romania', code: '+40', iso: 'RO', digits: 9, flag: '🇷🇴' },
  { name: 'Russia', code: '+7', iso: 'RU', digits: 10, flag: '🇷🇺' },
  { name: 'Rwanda', code: '+250', iso: 'RW', digits: 9, flag: '🇷🇼' },
  { name: 'Senegal', code: '+221', iso: 'SN', digits: 9, flag: '🇸🇳' },
  { name: 'Serbia', code: '+381', iso: 'RS', digits: 9, flag: '🇷🇸' },
  { name: 'Slovakia', code: '+421', iso: 'SK', digits: 9, flag: '🇸🇰' },
  { name: 'Slovenia', code: '+386', iso: 'SI', digits: 8, flag: '🇸🇮' },
  { name: 'South Africa', code: '+27', iso: 'ZA', digits: 9, flag: '🇿🇦' },
  { name: 'South Korea', code: '+82', iso: 'KR', digits: 10, flag: '🇰🇷' },
  { name: 'Spain', code: '+34', iso: 'ES', digits: 9, flag: '🇪🇸' },
  { name: 'Sri Lanka', code: '+94', iso: 'LK', digits: 9, flag: '🇱🇰' },
  { name: 'Sudan', code: '+249', iso: 'SD', digits: 9, flag: '🇸🇩' },
  { name: 'Sweden', code: '+46', iso: 'SE', digits: 9, flag: '🇸🇪' },
  { name: 'Switzerland', code: '+41', iso: 'CH', digits: 9, flag: '🇨🇭' },
  { name: 'Syria', code: '+963', iso: 'SY', digits: 9, flag: '🇸🇾' },
  { name: 'Taiwan', code: '+886', iso: 'TW', digits: 9, flag: '🇹🇼' },
  { name: 'Tanzania', code: '+255', iso: 'TZ', digits: 9, flag: '🇹🇿' },
  { name: 'Thailand', code: '+66', iso: 'TH', digits: 9, flag: '🇹🇭' },
  { name: 'Tunisia', code: '+216', iso: 'TN', digits: 8, flag: '🇹🇳' },
  { name: 'Turkey', code: '+90', iso: 'TR', digits: 10, flag: '🇹🇷' },
  { name: 'Uganda', code: '+256', iso: 'UG', digits: 9, flag: '🇺🇬' },
  { name: 'Ukraine', code: '+380', iso: 'UA', digits: 9, flag: '🇺🇦' },
  { name: 'Uruguay', code: '+598', iso: 'UY', digits: 8, flag: '🇺🇾' },
  { name: 'Uzbekistan', code: '+998', iso: 'UZ', digits: 9, flag: '🇺🇿' },
  { name: 'Venezuela', code: '+58', iso: 'VE', digits: 10, flag: '🇻🇪' },
  { name: 'Vietnam', code: '+84', iso: 'VN', digits: 9, flag: '🇻🇳' },
  { name: 'Yemen', code: '+967', iso: 'YE', digits: 9, flag: '🇾🇪' },
  { name: 'Zambia', code: '+260', iso: 'ZM', digits: 9, flag: '🇿🇲' },
  { name: 'Zimbabwe', code: '+263', iso: 'ZW', digits: 9, flag: '🇿🇼' }
]

export function getCountryByCode(code = '+91') {
  const normalized = String(code || '').trim()
  return countryPhoneCodes.find(c => c.code === normalized) || countryPhoneCodes[0]
}

export function getCountryDigits(code = '+91') {
  return getCountryByCode(code).digits
}
