# Generated by Django 5.2.17 on 2026-10-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacychatthread',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pharmacychatthread',
            name='patient',
        ),
        migrations.DeleteModel(
            name='PharmacyChatMessage',
        ),
        migrations.DeleteModel(
            name='PharmacyChatThread',
        ),
    ]
