# Generated by Django 5.2.17 on 2026-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_pharmacychatthread_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyrefund',
            name='destination',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacyrefund',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pharmacyrefund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
