# Generated by Django 5.2.17 on 2026-10-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_pharmacyrefund_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyorder',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on delivery'), ('card', 'Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('bank_transfer', 'Bank transfer')], default='cash_on_delivery', max_length=24),
        ),
    ]
