# Generated by Django 5.2.17 on 2026-10-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_pharmacyorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyorder',
            name='plan_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
