# Generated by Django 5.2.17 on 2026-10-03 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDoctor',
            fields=[
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('rating', models.CharField(blank=True, max_length=30)),
                ('reviews', models.CharField(blank=True, max_length=30)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('initials', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(default='teal', max_length=40)),
                ('next', models.CharField(blank=True, max_length=120)),
                ('consultation_type', models.CharField(default='Online & In-Person', max_length=80)),
                ('photo', models.URLField(blank=True, max_length=500)),
                ('offer_text', models.CharField(blank=True, max_length=300)),
                ('verified', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='verified', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=120)),
                ('development_key', models.CharField(max_length=120)),
                ('synced_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('model_label', 'development_key'), name='dashboard_unique_dev_sync_record')],
            },
        ),
        migrations.CreateModel(
            name='PlatformReview',
            fields=[
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, max_length=64)),
                ('patient_name', models.CharField(max_length=200)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('is_seed', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, related_name='platform_reviews', to='dashboard.platformdoctor')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('date_of_birth', models.CharField(blank=True, max_length=40)),
                ('blood_group', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('partner', 'Partner')], max_length=16)),
                ('status', models.CharField(default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wallet_transactions', models.JSONField(blank=True, default=list)),
                ('family_members', models.JSONField(blank=True, default=list)),
                ('addresses', models.JSONField(blank=True, default=list)),
                ('partner_role', models.CharField(blank=True, max_length=100)),
                ('availability', models.CharField(default='available', max_length=20)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_users', to='dashboard.platformdoctor')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='platformdoctor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_doctor_profiles', to='dashboard.platformuser'),
        ),
    ]
