# Generated by Django 5.2.17 on 2026-10-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
