# Generated by Django 5.2.17 on 2026-10-05 11:34

import django.db.models.deletion
from collections import defaultdict
from django.db import migrations, models


def link_unambiguous_partner_accounts(apps, schema_editor):
    PlatformUser = apps.get_model("dashboard", "PlatformUser")
    HealthcareProvider = apps.get_model("providers", "HealthcareProvider")
    database = schema_editor.connection.alias
    partners = list(
        PlatformUser.objects.using(database)
        .filter(role="partner", healthcare_provider__isnull=True)
        .only("id", "email", "mobile")
    )
    providers = list(
        HealthcareProvider.objects.using(database)
        .filter(platform_user__isnull=True)
        .only("id", "email", "phone")
    )

    def normalized(value):
        return str(value or "").strip().casefold()

    def digits(value):
        return "".join(character for character in str(value or "") if character.isdigit())

    partners_by_email = defaultdict(list)
    providers_by_email = defaultdict(list)
    partners_by_phone = defaultdict(list)
    providers_by_phone = defaultdict(list)
    for partner in partners:
        if normalized(partner.email):
            partners_by_email[normalized(partner.email)].append(partner)
        if digits(partner.mobile):
            partners_by_phone[digits(partner.mobile)].append(partner)
    for provider in providers:
        if normalized(provider.email):
            providers_by_email[normalized(provider.email)].append(provider)
        if digits(provider.phone):
            providers_by_phone[digits(provider.phone)].append(provider)

    links = {}
    for email, matched_partners in partners_by_email.items():
        matched_providers = providers_by_email.get(email, [])
        if len(matched_partners) == len(matched_providers) == 1:
            links[matched_partners[0].pk] = matched_providers[0].pk

    used_provider_ids = set(links.values())
    for phone, matched_partners in partners_by_phone.items():
        matched_providers = providers_by_phone.get(phone, [])
        if len(matched_partners) != 1 or len(matched_providers) != 1:
            continue
        partner = matched_partners[0]
        provider = matched_providers[0]
        if partner.pk in links or provider.pk in used_provider_ids:
            continue
        if normalized(partner.email) and normalized(provider.email):
            continue
        links[partner.pk] = provider.pk
        used_provider_ids.add(provider.pk)

    for partner_id, provider_id in links.items():
        PlatformUser.objects.using(database).filter(pk=partner_id).update(
            healthcare_provider_id=provider_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_platformuser_password_hash'),
        ('providers', '0002_healthcareprovider_development_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='healthcare_provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_user', to='providers.healthcareprovider'),
        ),
        migrations.RunPython(
            link_unambiguous_partner_accounts,
            migrations.RunPython.noop,
        ),
    ]
