# Generated by Django 5.2.17 on 2026-10-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovider',
            name='development_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='is_development_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='development_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='is_development_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
