# Generated by Django 5.2.17 on 2026-10-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_seed_health_plan_catalog'),
        ('dashboard', '0003_platformuser_healthcare_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercetransaction',
            name='platform_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_transactions', to='dashboard.platformuser'),
        ),
        migrations.AddField(
            model_name='planorder',
            name='platform_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_orders', to='dashboard.platformuser'),
        ),
    ]
