# Generated by Django 5.2.17 on 2026-10-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_commercetransaction_platform_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12),
        ),
    ]
