# Generated by Django 5.2.17 on 2026-10-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_carepayment_payment_method_refundrequest_destination_and_more'),
        ('commerce', '0004_alter_planorder_status'),
        ('health_records', '0006_catalog_pricing_and_booking_details'),
        ('lab_tests', '0004_catalog_pricing_and_booking_details'),
        ('pharmacy', '0004_alter_pharmacyorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercetransaction',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_transactions', to='care.appointment'),
        ),
        migrations.AddField(
            model_name='commercetransaction',
            name='lab_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_transactions', to='health_records.labbooking'),
        ),
        migrations.AddField(
            model_name='commercetransaction',
            name='pharmacy_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_transactions', to='pharmacy.pharmacyorder'),
        ),
        migrations.AddField(
            model_name='commercetransaction',
            name='plan_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_transactions', to='commerce.planorder'),
        ),
        migrations.AddField(
            model_name='commercetransaction',
            name='scan_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_transactions', to='lab_tests.scanbooking'),
        ),
    ]
