# Generated by Django 5.2.17 on 2026-10-05 16:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_commercetransaction_appointment_and_more'),
        ('dashboard', '0003_platformuser_healthcare_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPlanCalculatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('doctor_visits_min', models.PositiveSmallIntegerField(default=1)),
                ('doctor_visits_max', models.PositiveSmallIntegerField(default=10)),
                ('doctor_visits_default', models.PositiveSmallIntegerField(default=2)),
                ('pharmacy_spend_min', models.PositiveSmallIntegerField(default=20)),
                ('pharmacy_spend_max', models.PositiveSmallIntegerField(default=400)),
                ('pharmacy_spend_step', models.PositiveSmallIntegerField(default=10)),
                ('pharmacy_spend_default', models.PositiveSmallIntegerField(default=80)),
                ('lab_spend_min', models.PositiveSmallIntegerField(default=50)),
                ('lab_spend_max', models.PositiveSmallIntegerField(default=800)),
                ('lab_spend_step', models.PositiveSmallIntegerField(default=25)),
                ('lab_spend_default', models.PositiveSmallIntegerField(default=200)),
                ('consultation_value', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health plan calculator configuration',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='healthplan',
            name='ambulance_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='healthplan',
            name='annual_checkup_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthplan',
            name='care_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthplan',
            name='custom_benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='healthplan',
            name='free_consultations_per_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthplan',
            name='free_home_sample_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthplan',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='healthplan',
            name='lab_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='healthplan',
            name='maximum_family_members',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='healthplan',
            name='pharmacy_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='planorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planorder',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='planorder',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='commerce.planorder'),
        ),
        migrations.AddField(
            model_name='planorder',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='planorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12),
        ),
        migrations.CreateModel(
            name='PlanFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=160)),
                ('relationship', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_plan_family_members', to='dashboard.platformuser')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='commerce.planorder')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HealthPlanBenefitUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('benefit_code', models.CharField(db_index=True, max_length=32)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('period_start', models.DateField(db_index=True)),
                ('source_type', models.CharField(max_length=32)),
                ('source_id', models.CharField(max_length=100)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefit_usage', to='commerce.planorder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'benefit_code', 'source_type', 'source_id'), name='commerce_unique_plan_benefit_event')],
            },
        ),
    ]
