# Generated by Django 5.2.17 on 2026-10-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_featuredpromotion_promotionalcontent'),
        ('marketing', '0002_promotion'),
    ]

    operations = [
    ]
