# Generated by Django 5.2.17 on 2026-10-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_merge_20261003_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='development_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_development_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='featuredpromotion',
            name='development_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='featuredpromotion',
            name='is_development_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='development_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_development_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='promotionalcontent',
            name='development_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promotionalcontent',
            name='is_development_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
