# Generated by Django 5.2.17 on 2026-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_doctorslotexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carepayment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('cash', 'Cash'), ('other', 'Not recorded')], default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='destination',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
