# Generated by Django 5.2.17 on 2026-10-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_alter_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carepayment',
            name='plan_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
