# Generated by Django 5.2.17 on 2026-10-04 18:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_healthcareprovider_development_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phlebotomist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('specimen', models.CharField(blank=True, max_length=100)),
                ('fasting_required', models.BooleanField(default=False)),
                ('turnaround_hours', models.PositiveSmallIntegerField(default=24)),
                ('biomarker_count', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='tests', to='lab_tests.labtestcategory')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabTestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tests', models.ManyToManyField(related_name='packages', to='lab_tests.labtest')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('modality', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('turnaround_hours', models.PositiveSmallIntegerField(default=24)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(limit_choices_to={'provider_type': 'diagnostic_centre'}, on_delete=django.db.models.deletion.PROTECT, related_name='radiology_services', to='providers.healthcareprovider')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
