# Generated by Django 5.2.17 on 2026-10-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        ('lab_tests', '0002_organprofilecategory_healthcheckbundle_and_more'),
        ('providers', '0002_healthcareprovider_development_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('scheduled', 'Scheduled'), ('done', 'Done'), ('report_uploaded', 'Report Uploaded'), ('cancelled', 'Cancelled')], db_index=True, default='booked', max_length=20)),
                ('report_file', models.FileField(blank=True, upload_to='health-records/scan-reports/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(limit_choices_to={'provider_type': 'diagnostic_centre'}, on_delete=django.db.models.deletion.PROTECT, related_name='scan_bookings', to='providers.healthcareprovider')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_bookings', to='care.carepatient')),
                ('radiology_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='lab_tests.radiologyservice')),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
            },
        ),
    ]
