# Generated by Django 5.2.17 on 2026-10-04 19:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0003_scanbooking'),
        ('providers', '0002_healthcareprovider_development_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='centre',
            field=models.ForeignKey(blank=True, limit_choices_to={'provider_type': 'diagnostic_centre'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='providers.healthcareprovider'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='labtest',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='labtestpackage',
            name='badge',
            field=models.CharField(blank=True, choices=[('popular', 'Popular'), ('best_value', 'Best Value'), ('fever_special', 'Fever Special')], max_length=20),
        ),
        migrations.AddField(
            model_name='labtestpackage',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='labtestpackage',
            name='turnaround_hours',
            field=models.PositiveSmallIntegerField(default=24),
        ),
    ]
