# Generated by Django 5.2.17 on 2026-10-03 18:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('allergy', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='care.carepatient')),
            ],
            options={
                'verbose_name_plural': 'allergies',
                'ordering': ['allergy', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('test_name', models.CharField(max_length=200)),
                ('specimen_date', models.DateField()),
                ('phlebotomist', models.CharField(blank=True, max_length=150)),
                ('pathologist', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('clinical_summary', models.TextField(blank=True)),
                ('report_pdf_url', models.URLField(blank=True, max_length=1000)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_bookings', to='care.carepatient')),
            ],
            options={
                'ordering': ['-specimen_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('prescription_number', models.CharField(blank=True, max_length=100)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('diagnosis', models.TextField(blank=True)),
                ('medicines', models.JSONField(blank=True, default=list)),
                ('instructions', models.TextField(blank=True)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12)),
                ('pdf_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_uploads', to='care.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_uploads', to='care.carepatient')),
            ],
            options={
                'ordering': ['-issued_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('vaccine', models.CharField(max_length=200)),
                ('administered_on', models.DateField()),
                ('dose', models.CharField(max_length=100)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='care.carepatient')),
            ],
            options={
                'ordering': ['-administered_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_key', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ('is_development_data', models.BooleanField(db_index=True, default=False)),
                ('recorded_at', models.DateTimeField()),
                ('systolic_bp', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('diastolic_bp', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('sugar', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('pulse', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='care.carepatient')),
            ],
            options={
                'ordering': ['recorded_at', 'id'],
            },
        ),
    ]
