# Generated by Django 5.2.17 on 2026-10-04 17:12

import django.db.models.deletion
import health_records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionupload',
            name='file',
            field=models.FileField(blank=True, upload_to=health_records.models.prescription_file_upload_to),
        ),
        migrations.AddField(
            model_name='prescriptionupload',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescriptionupload',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescriptionupload',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionupload',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pharmacy_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
