# Generated by Django 5.2.17 on 2026-10-04 18:51

import django.db.models.deletion
import health_records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_prescriptionupload_file_and_more'),
        ('lab_tests', '0001_initial'),
        ('providers', '0002_healthcareprovider_development_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbooking',
            name='assigned_phlebotomist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_bookings', to='lab_tests.phlebotomist'),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_bookings', to='providers.healthcareprovider'),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='lab_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='lab_tests.labtestpackage'),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='lab_tests.labtest'),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='report_file',
            field=models.FileField(blank=True, upload_to=health_records.models.lab_report_upload_to),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='labbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('assigned', 'Assigned'), ('collected', 'Collected'), ('in_lab', 'In lab'), ('report_ready', 'Report ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12),
        ),
    ]
