# Generated by Django 5.2.17 on 2026-10-04 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0003_labbooking_assigned_phlebotomist_labbooking_centre_and_more'),
        ('lab_tests', '0002_organprofilecategory_healthcheckbundle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbooking',
            name='health_check_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='lab_tests.healthcheckbundle'),
        ),
    ]
