# Generated by Django 5.2.17 on 2026-10-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0004_labbooking_health_check_bundle'),
        ('lab_tests', '0003_scanbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbooking',
            name='lab_packages',
            field=models.ManyToManyField(blank=True, related_name='multi_bookings', to='lab_tests.labtestpackage'),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='lab_tests',
            field=models.ManyToManyField(blank=True, related_name='multi_bookings', to='lab_tests.labtest'),
        ),
    ]
