# Generated by Django 5.2.17 on 2026-10-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0005_labbooking_lab_packages_labbooking_lab_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbooking',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='time_slot',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
