# Generated by Django 5.2.17 on 2026-10-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0006_catalog_pricing_and_booking_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbooking',
            name='plan_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
