# Generated by Django 5.2.17 on 2026-10-05 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Tatito Health+", max_length=150),
                ),
                ("logo_url", models.CharField(blank=True, max_length=500)),
                ("favicon_url", models.CharField(blank=True, max_length=500)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=30)),
                ("contact_address", models.TextField(blank=True)),
                ("social_facebook", models.URLField(blank=True)),
                ("social_instagram", models.URLField(blank=True)),
                ("social_twitter", models.URLField(blank=True)),
                ("social_linkedin", models.URLField(blank=True)),
                ("footer_text", models.TextField(blank=True)),
                ("announcement_enabled", models.BooleanField(default=False)),
                ("announcement_text", models.TextField(blank=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("currency_symbol", models.CharField(default="₹", max_length=10)),
                ("date_format", models.CharField(default="DD/MM/YYYY", max_length=50)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=100)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("delivery_fee_rule", models.CharField(default="flat", max_length=100)),
                (
                    "delivery_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_gateway_name", models.CharField(blank=True, max_length=100)),
                (
                    "payment_gateway_mode",
                    models.CharField(default="test", max_length=30),
                ),
                (
                    "payment_gateway_public_key",
                    models.CharField(blank=True, max_length=500),
                ),
                ("otp_enabled", models.BooleanField(default=True)),
                ("otp_expiry_minutes", models.PositiveIntegerField(default=5)),
                ("session_timeout_minutes", models.PositiveIntegerField(default=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
            },
        ),
    ]
